<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit596d81f91763018e12dc9edc3d2c9745
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MessageBird\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MessageBird\\' => 
        array (
            0 => __DIR__ . '/..' . '/messagebird/php-rest-api/src/MessageBird',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit596d81f91763018e12dc9edc3d2c9745::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit596d81f91763018e12dc9edc3d2c9745::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit596d81f91763018e12dc9edc3d2c9745::$classMap;

        }, null, ClassLoader::class);
    }
}
